# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.2.5
    

jobs:
  build:
    docker:
    # specify the version you desire here
    - image: cimg/node:12.22.12-browsers

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/WebdriverIO_v5_TypeScript

    steps:
    - browser-tools/install-chrome
    - browser-tools/install-chromedriver
    - checkout

    - run: |
        google-chrome --version
        node --version
    #     java --version

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Run Tests
        command: yarn test

    - run:
        name: Generate Allure Report
        command: npm run report-ci
        when: always

    - store_artifacts:
        name: Upload Allure Report
        path: allure-report/
